FROM jenkins/jenkins:lts

USER root

# Replace the default repository with official ones
RUN echo "deb http://deb.debian.org/debian stable main" > /etc/apt/sources.list

RUN apt-get update -qq && apt-get install -y \
    docker.io \
    make \
    g++ \
    curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
